export default {
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
  },
  leftCol: {
    flex: 4,
    backgroundColor: '#F2F9EC', // Solid light matcha color
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  logoGlow: {
    shadowColor: '#4A924C',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 40,
    elevation: 20,
    marginBottom: 32,
    borderRadius: 36,
  },
  logoWrap: {
    width: 110,
    height: 110,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#49934F',
  },
  brandTitle: {
    fontSize: 40,
    fontWeight: '900',
    color: '#064E3B',
    letterSpacing: 1,
    textAlign: 'center',
    paddingHorizontal: 20,
    lineHeight: 50,
  },
  rightCol: {
    flex: 6,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 60,
    backgroundColor: '#FFFFFF', // Solid pure white
    position: 'relative',
    overflow: 'hidden',
  },
  decor1: { position: 'absolute', top: '15%', left: '10%', fontSize: 90, opacity: 0.08, transform: [{ rotate: '-20deg' }] },
  decor2: { position: 'absolute', bottom: '15%', right: '15%', fontSize: 110, opacity: 0.07, transform: [{ rotate: '15deg' }] },
  decor3: { position: 'absolute', top: '40%', right: '-15%', fontSize: 130, opacity: 0.06, transform: [{ rotate: '45deg' }] },
  decor4: { position: 'absolute', top: '20%', right: '10%', fontSize: 80, opacity: 0.06, transform: [{ rotate: '60deg' }] },
  decor5: { position: 'absolute', bottom: '20%', left: '5%', fontSize: 100, opacity: 0.06, transform: [{ rotate: '-30deg' }] },
  card: {
    width: '100%',
    maxWidth: 500,
    backgroundColor: '#FAFCF8', // Rất nhạt của màu Xanh để khác màu nền
    borderRadius: 24,
    padding: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 32,
    elevation: 15,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    marginBottom: 40,
  },
  backBtnBtn: {
    position: 'absolute',
    left: 0,
    zIndex: 10,
  },
  title: {
    fontSize: 32,
    fontWeight: '900',
    color: '#064E3B',
    textAlign: 'center',
  },
  inputWrap: {
    marginBottom: 24,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  input: {
    height: 54,
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 15,
  },
  pwInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingRight: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  pwInput: {
    flex: 1,
    height: 54,
    paddingHorizontal: 16,
    fontSize: 15,
    color: '#1E293B',
  },
  forgotPwText: {
    fontSize: 13,
    color: '#4A924C',
    fontWeight: '700',
    fontStyle: 'italic',
    textAlign: 'right',
    marginTop: 4,
    marginBottom: 32,
  },
  btnWrapper: {
    width: '100%',
    marginBottom: 32,
  },
  btnPrimary: {
    paddingVertical: 18,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#49934F',
    shadowColor: '#4A924C',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  btnPrimaryText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  footerLinkWrap: {
    alignItems: 'center',
  },
  footerText: {
    color: '#64748B',
    fontSize: 14,
  },
  linkText: {
    color: '#4A924C',
    fontWeight: '800',
  },
  errorText: {
    color: '#EF4444',
    fontSize: 13,
    marginTop: 6,
    textAlign: 'left',
    fontWeight: '500',
    paddingLeft: 4,
  },
};
