import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFFFF' },
  gradientBg: { flex: 1 },
  splitContainer: { flex: 1, flexDirection: 'row' },

  // ================= PANE TRÁI (60%) =================
  leftPane: { flex: 0.6, padding: 24, backgroundColor: '#FFFFFF' },
  headerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  backBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 6, elevation: 2 },
  headerTitle: { fontSize: 24, fontWeight: '700', color: '#1E293B' },
  headerSubtitle: { fontSize: 14, color: '#64748B', fontWeight: '500', marginTop: 2 },
  editBtnLayered: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 22, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.08, shadowRadius: 15, elevation: 4 },

  // Info Card (Table/Reservation Info)
  infoCardWrapper: { borderRadius: 28, overflow: 'hidden', marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.05, shadowRadius: 20, elevation: 6 },
  infoCard: { padding: 24 },
  infoCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 },
  tableTitleWrap: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  tableTitle: { fontSize: 20, fontWeight: '700', color: '#1E293B' },
  tableStatusBadge: { backgroundColor: 'rgba(76, 175, 80, 0.1)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  tableStatusText: { color: '#4CAF50', fontSize: 13, fontWeight: '600' },
  customerNameRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  customerNameText: { fontSize: 16, fontWeight: '600', color: '#334155' },
  customerPhoneText: { fontSize: 14, color: '#64748B' },
  statsRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8, paddingTop: 16, borderTopWidth: 1, borderTopColor: 'rgba(0,0,0,0.05)' },
  statItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  statText: { fontSize: 14, color: '#475569', fontWeight: '500' },
  timeHighlight: { color: '#FF9800', fontWeight: '700' },

  // Modern Stepper Row (Full Width)
  stepperFullRow: { width: '100%', borderRadius: 100, overflow: 'hidden', marginBottom: 28, shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.1, shadowRadius: 20, elevation: 8 },
  stepperPill: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 12 },
  stepNode: { alignItems: 'center', width: 68 },
  stepLine: { flex: 1, height: 20, justifyContent: 'center', marginTop: -16 },
  stepCircle: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center', marginBottom: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 2, position: 'relative' },

  stepCircleCompleted: { backgroundColor: '#8BA367' },
  stepCircleActive: { backgroundColor: '#8BA367', borderWidth: 2, borderColor: '#FFFFFF' },
  stepCirclePending: { backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#E2E8F0' },

  stepNumberText: { fontSize: 13, fontWeight: '700' },
  stepNumberActive: { color: '#FFFFFF' },
  stepNumberPending: { color: '#94A3B8' },

  activeGlow: { position: 'absolute', top: -4, left: -4, right: -4, bottom: -4, borderRadius: 20, borderWidth: 2, borderColor: '#FFB74D', opacity: 0.5 },

  stepLabel: { fontSize: 11, fontWeight: '600', textAlign: 'center' },
  stepLabelCompleted: { color: '#8BA367' },
  stepLabelActive: { color: '#1E293B', fontWeight: '800' },
  stepLabelPending: { color: '#64748B' },

  stepperTrack: { position: 'absolute', top: 20, left: '12%', right: '12%', height: 2, zIndex: 0 },
  stepLine: { flex: 1, height: 2, marginTop: -16 },

  // Left Product Scroll
  leftProductScroll: { flex: 1 },
  productGrid: { gap: 12, paddingBottom: 20 },
  productCard: { flexDirection: 'row', paddingVertical: 12, alignItems: 'center', gap: 16, borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.05)' },
  productThumb: { width: 64, height: 64, backgroundColor: 'rgba(0,0,0,0.03)', borderRadius: 12, justifyContent: 'center', alignItems: 'center', position: 'relative' },
  productQtyBadge: { position: 'absolute', top: -6, right: -6, backgroundColor: '#1E293B', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8 },
  productQtyText: { color: '#FFFFFF', fontSize: 10, fontWeight: '700' },
  productName: { fontSize: 16, fontWeight: '600', color: '#1E293B', marginBottom: 4 },
  productMeta: { fontSize: 13, color: '#64748B' },
  productPrice: { fontSize: 15, fontWeight: '700', color: '#8BA367', marginTop: 4 },

  // Product List Frame (New)
  productListWrapper: { flex: 1, borderRadius: 28, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 12 }, shadowOpacity: 0.06, shadowRadius: 24, elevation: 8, backgroundColor: '#FFFFFF' },
  productListGradient: { flex: 1, padding: 20 },
  productListHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  productListTitle: { fontSize: 18, fontWeight: '700', color: '#1E293B' },
  itemCountBadge: { backgroundColor: '#F1F5F9', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10 },
  itemCountText: { fontSize: 12, fontWeight: '600', color: '#64748B' },

  // ================= PANE PHẢI (40%) =================
  rightPane: { flex: 0.4, padding: 24, backgroundColor: '#F8FAFC', gap: 20 },
  rightCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 6,
  },

  receiptHeader: { marginBottom: 24 },
  receiptTitle: { fontSize: 13, fontWeight: '800', color: '#94A3B8', letterSpacing: 1.5, textTransform: 'uppercase' },
  receiptStatusText: { fontSize: 14, color: '#64748B', marginTop: 4, fontWeight: '600' },
  receiptDivider: { height: 1, backgroundColor: 'rgba(0,0,0,0.05)', marginVertical: 24 },

  summaryItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  summaryLabel: { fontSize: 15, color: '#94A3B8', fontWeight: '700' },
  summaryValue: { fontSize: 16, color: '#1E293B', fontWeight: '800' },

  actionBtnGridVertical: { gap: 12 },
  actionBtnLayered: { flexDirection: 'row', backgroundColor: '#F8FAFC', borderRadius: 20, padding: 14, alignItems: 'center', gap: 14, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.04, shadowRadius: 10, elevation: 4 },
  actionBtnIconWrap: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center' },
  actionBtnInfo: { flex: 1 },
  actionBtnTitle: { fontSize: 15, fontWeight: '700', color: '#1E293B' },
  actionBtnSub: { fontSize: 12, color: '#94A3B8', marginTop: 2, fontWeight: '500' },
  actionBtnActive: { borderWidth: 2, borderColor: '#8BA367', backgroundColor: '#F0FDF4' },

  // Bottom Payment Area (Integrated)
  receiptPaymentBox: { marginTop: 'auto', paddingTop: 20, borderTopWidth: 1, borderTopColor: 'rgba(0,0,0,0.05)' },
  grandTotalItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 16, paddingTop: 16, borderTopWidth: 1, borderTopColor: 'rgba(0,0,0,0.06)' },
  grandTotalLabel: { fontSize: 16, fontWeight: '800', color: '#1E293B', letterSpacing: 0.5 },
  grandTotalValue: { fontSize: 28, fontWeight: '900', color: '#E11D48' },

  actionBtnRow: { flexDirection: 'row', gap: 12, marginTop: 16 },
  actionBtnBase: { borderRadius: 20, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.15, shadowRadius: 12, elevation: 6 },
  actionBtnInner: { paddingVertical: 16, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  actionBtnText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800', letterSpacing: 0.5 },

  // Summary Items (used in footer box)
  grandTotalItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  grandTotalLabel: { fontSize: 20, fontWeight: '900', color: '#1E293B' },
  grandTotalValue: { fontSize: 32, fontWeight: '900', color: '#8BA367' },

  // Compact List
  compactItem: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  compactItemName: { flex: 1, fontSize: 14, color: '#334155', fontWeight: '500' },
  compactItemPrice: { fontSize: 14, color: '#1E293B', fontWeight: '600', marginLeft: 10 },
  receiptSectionTitle: { fontSize: 13, fontWeight: '800', color: '#94A3B8', textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 20 },
  iptDashDivider: { height: 1, borderWidth: 1, borderColor: '#E2E8F0', borderStyle: 'dashed', marginVertical: 20 },

  // Action Buttons (Member, Voucher, Fees)
  actionBtnGrid: { gap: 12, marginTop: 10 },
  actionBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F8FAFC', padding: 16, borderRadius: 16, gap: 12 },
  actionBtnActive: { backgroundColor: '#F0FDF4', borderColor: '#86EFAC' },
  actionBtnInfo: { flex: 1 },
  actionBtnTitle: { fontSize: 15, fontWeight: '600', color: '#1E293B' },
  actionBtnSub: { fontSize: 13, color: '#64748B', marginTop: 2 },

  // Footer
  receiptFooter: { backgroundColor: '#F8FAFC', padding: 20, borderTopLeftRadius: 24, borderTopRightRadius: 24 },
  summaryItem: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  summaryLabel: { fontSize: 14, color: '#64748B', fontWeight: '500' },
  summaryValue: { fontSize: 15, fontWeight: '600', color: '#1E293B' },
  grandTotalItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, paddingTop: 16, borderTopWidth: 1, borderTopColor: '#E2E8F0', borderStyle: 'solid' },
  grandTotalLabel: { fontSize: 18, fontWeight: '800', color: '#1E293B' },
  grandTotalValue: { fontSize: 26, fontWeight: '800', color: '#D32F2F' },
  payBigBtn: { height: 56, backgroundColor: '#8BA367', borderRadius: 16, justifyContent: 'center', alignItems: 'center', shadowColor: '#8BA367', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 12, elevation: 8 },
  payBigBtnText: { color: '#FFFFFF', fontSize: 18, fontWeight: '700', letterSpacing: 1 },

  // =============== MODAL CHUNG ===============
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { backgroundColor: '#FFFFFF', width: 420, borderRadius: 24, padding: 24, maxHeight: '90%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20 },
  modalTitle: { fontSize: 20, fontWeight: '700', color: '#1E293B', marginBottom: 4 },
  modalSubtitle: { fontSize: 14, color: '#64748B' },
  closeBtn: { width: 32, height: 32, justifyContent: 'center', alignItems: 'center', backgroundColor: '#F1F5F9', borderRadius: 16 },

  // Custom Modal Form Parts
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
  },
  searchPill: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 50,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
    justifyContent: 'center',
  },
  searchInput: {
    fontSize: 15,
    fontWeight: '500',
    color: '#1E293B',
    paddingVertical: 12,
  },
  searchSquareBtn: {
    width: 50,
    height: 50,
    borderRadius: 16,
    backgroundColor: '#1E293B',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },

  // Other old modal definitions needed to prevent crash
  statusList: { gap: 12 },
  statusItem: { flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: 16, borderWidth: 1.5, borderColor: '#F1F5F9', gap: 16 },
  statusItemActive: { backgroundColor: 'rgba(139, 163, 103, 0.05)', borderColor: 'rgba(139, 163, 103, 0.3)' },
  statusIconContainer: { width: 48, height: 48, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  statusLabelContainer: { flex: 1 },
  statusLabelMain: { fontSize: 16, fontWeight: '600', color: '#1E293B' },
  statusLabelSub: { fontSize: 12, color: '#64748B', marginTop: 2 },
  checkIcon: { width: 24, height: 24, borderRadius: 12, backgroundColor: 'rgba(139, 163, 103, 0.1)', justifyContent: 'center', alignItems: 'center' },
  modalFooter: { marginTop: 20, borderTopWidth: 1, borderTopColor: '#F1F5F9', paddingTop: 20 },
  modalCloseBtn: { height: 50, borderRadius: 16, borderWidth: 1, borderColor: '#E2E8F0', justifyContent: 'center', alignItems: 'center' },
  modalCloseBtnText: { fontSize: 15, fontWeight: '600', color: '#1E293B' },

  feeChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, backgroundColor: '#F1F5F9', borderWidth: 1, borderColor: '#E2E8F0' },
  feeChipActive: { backgroundColor: '#8BA367', borderColor: '#8BA367' },
  feeChipText: { fontSize: 13, color: '#64748B', fontWeight: '500' },
  feeChipTextActive: { color: '#FFFFFF' },
  payBtn: { height: 50, backgroundColor: '#8BA367', borderRadius: 16, justifyContent: 'center', alignItems: 'center' },
  payBtnText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' },

  // Voucher Scroll
  voucherScroll: { paddingVertical: 10 },
  voucherCard: { 
    width: '100%', 
    backgroundColor: '#FFFFFF', 
    borderRadius: 16, 
    marginBottom: 16,
    borderWidth: 2, 
    borderColor: '#E2E8F0',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  voucherCardSelected: { 
    borderColor: '#3B82F6',
    backgroundColor: '#F0F9FF',
  },
  voucherCardDisabled: {
    opacity: 0.6,
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
  },
  couponHeader: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  couponHeaderText: { fontSize: 18, fontWeight: '800', color: '#3B82F6' },
  couponHeaderDate: { fontSize: 11, color: '#64748B', fontWeight: '600', backgroundColor: '#F1F5F9', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  couponDashedLine: {
    height: 1,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
    marginHorizontal: -2,
  },
  leftCutoutMask: {
    position: 'absolute',
    left: -2,
    top: '32%',
    width: 14,
    height: 24,
    overflow: 'hidden',
    zIndex: 10,
  },
  leftCutoutCircle: {
    position: 'absolute',
    left: -12,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E2E8F0',
  },
  rightCutoutMask: {
    position: 'absolute',
    right: -2,
    top: '32%',
    width: 14,
    height: 24,
    overflow: 'hidden',
    zIndex: 10,
  },
  rightCutoutCircle: {
    position: 'absolute',
    left: 2,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E2E8F0',
  },
  voucherInfo: { 
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  voucherTitle: { fontSize: 16, fontWeight: '800', color: '#1E293B' },
  voucherSub: { fontSize: 13, color: '#64748B', marginTop: 2, fontWeight: '500' },
  voucherError: { fontSize: 12, color: '#EF4444', marginTop: 6, fontWeight: '700' },
  checkbox: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: '#CBD5E1', justifyContent: 'center', alignItems: 'center' },
  checkboxSelected: { backgroundColor: '#3B82F6', borderColor: '#3B82F6' },
  // ================= PAYMENT DASHBOARD MODAL =================
  paymentModalContent: {
    backgroundColor: '#FFFFFF',
    width: 900,
    height: 600,
    borderRadius: 32,
    flexDirection: 'row',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.15,
    shadowRadius: 40,
    elevation: 24,
  },
  paymentLeftPane: {
    flex: 0.45,
    backgroundColor: '#F8FAFC',
    padding: 24,
    borderRightWidth: 1,
    borderRightColor: '#F1F5F9',
  },
  paymentRightPane: {
    flex: 0.55,
    padding: 24,
  },
  billSectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#94A3B8',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 16,
  },
  billItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  billItemName: { fontSize: 14, color: '#334155', flex: 1 },
  billItemQty: { fontSize: 14, color: '#94A3B8', marginHorizontal: 8 },
  billItemPrice: { fontSize: 14, color: '#1E293B', fontWeight: '600' },

  paymentMethodGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  methodTab: {
    flex: 1,
    height: 80,
    borderRadius: 20,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  methodTabActive: {
    backgroundColor: '#F0FDF4',
    borderColor: '#8BA367',
  },
  methodTabText: { fontSize: 13, fontWeight: '700', color: '#64748B', marginTop: 8 },
  methodTabTextActive: { color: '#166534' },

  qrContainer: {
    backgroundColor: '#F8FAFC',
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 20,
    marginBottom: 40,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
    alignSelf: 'center',
    width: '100%',
  },
  qrLabel: { fontSize: 13, color: '#64748B', fontWeight: '800', marginBottom: 12, letterSpacing: 1 },
  dashboardQRImg: {
    width: 140,
    height: 140,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  qrInfoText: {
    fontSize: 15,
    color: '#1E293B',
    fontWeight: '800',
    marginTop: 12,
    textAlign: 'center',
  },
  qrSubInfoText: {
    fontSize: 12,
    color: '#64748B',
    textAlign: 'center',
    marginTop: 4,
    fontWeight: '600',
  },
  
  cashContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    gap: 12,
  },
  cashIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#F0FDF4',
    justifyContent: 'center',
    alignItems: 'center',
  },

  paymentActionRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 'auto',
  },
  exportBillBtn: {
    flex: 1,
    height: 54,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  exportBillText: { fontSize: 14, fontWeight: '700', color: '#64748B' },
  confirmPayBtn: {
    flex: 1,
    height: 54,
    borderRadius: 18,
    overflow: 'hidden',
  },
  confirmPayBtnInner: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmPayText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },

  // ================= RECEIPT (INVOICE) MODAL =================
  receiptModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  receiptPaper: {
    backgroundColor: '#FFFFFF',
    width: 450,
    height: 650,
    borderRadius: 12,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 20,
  },
  receiptBrand: {
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
    color: '#1E293B',
    marginBottom: 4,
  },
  receiptSubBrand: {
    fontSize: 12,
    textAlign: 'center',
    color: '#64748B',
    marginBottom: 20,
  },
  receiptRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  receiptLabel: { fontSize: 13, color: '#64748B' },
  receiptValue: { fontSize: 13, fontWeight: '600', color: '#1E293B' },
  receiptItemName: { fontSize: 13, flex: 1, color: '#1E293B' },
  receiptItemQty: { fontSize: 13, width: 30, textAlign: 'center', color: '#64748B' },
  receiptItemPrice: { fontSize: 13, width: 80, textAlign: 'right', color: '#1E293B', fontWeight: '600' },
  
  receiptTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    borderStyle: 'dashed',
  },
  receiptTotalLabel: { fontSize: 16, fontWeight: '800', color: '#1E293B' },
  receiptTotalValue: { fontSize: 18, fontWeight: '900', color: '#000' },

  receiptQR: {
    width: 140,
    height: 140,
    alignSelf: 'center',
    marginTop: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  receiptQRImg: {
    width: 130,
    height: 130,
  },

  toastContainer: {
    position: 'absolute',
    top: 40,
    alignSelf: 'center',
    backgroundColor: '#1E293B',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 100,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    zIndex: 9999,
  },
  toastText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },
  toastWarning: {
    backgroundColor: '#FFFBEB',
    borderWidth: 1,
    borderColor: '#F59E0B',
  },
  toastTextWarning: {
    color: '#D97706',
  },
});
