import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
    bodyScroll: { padding: 16, paddingBottom: 100 },
    sectionCard: {
        backgroundColor: '#FFFFFF', borderRadius: 20, padding: 16, marginBottom: 20,
        shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 10, elevation: 3
    },
    sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
    sectionIconBox: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#FFF7ED', justifyContent: 'center', alignItems: 'center' },
    sectionIconBoxGreen: { backgroundColor: '#F0FDF4' },
    sectionTitleRow: { marginLeft: 12, flexDirection: 'row', alignItems: 'center', flex: 1 },
    sectionTitle: { fontSize: 17, fontWeight: '800', color: '#1E2939' },
    badgeRed: { backgroundColor: '#FEF2F2', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10, marginLeft: 8 },
    badgeRedText: { color: '#EF4444', fontSize: 12, fontWeight: '700' },
    badgeGreen: { backgroundColor: '#F0FDF4', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10, marginLeft: 8 },
    badgeGreenText: { color: '#10B981', fontSize: 12, fontWeight: '700' },

    nestedScrollWrap: { maxHeight: 280 },
    pendItem: { borderBottomWidth: 1, borderBottomColor: '#F3F4F6', paddingVertical: 14 },
    pendTopRow: { flexDirection: 'row', justifyContent: 'space-between' },
    staffBasicInfo: { flex: 1 },
    staffName: { fontSize: 15, fontWeight: '700', color: '#1E2939' },
    staffRole: { fontSize: 13, color: '#64748B', marginTop: 2, fontWeight: '500' },
    staffEmail: { fontSize: 12, color: '#9CA3AF', marginTop: 1 },
    dateCol: { alignItems: 'flex-end' },
    dateLabel: { fontSize: 11, color: '#9CA3AF', marginBottom: 2 },
    dateValue: { fontSize: 12, fontWeight: '600', color: '#64748B' },
    pendActionRow: { flexDirection: 'row', marginTop: 12, gap: 10 },
    btnAccept: { flex: 1, height: 38, backgroundColor: '#10B981', borderRadius: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
    btnAcceptText: { color: '#FFF', fontSize: 13, fontWeight: '700' },
    btnReject: { width: 38, height: 38, borderRadius: 10, backgroundColor: '#F3F4F6', justifyContent: 'center', alignItems: 'center' },

    cardSearchRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
    cardSearchInputWrap: { flex: 1, height: 44, backgroundColor: '#F9FAFB', borderRadius: 12, borderHorizontal: 4, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12 },
    cardSearchInput: { flex: 1, marginLeft: 8, fontSize: 14, color: '#1E2939' },
    cardFilterBtn: { width: 44, height: 44, backgroundColor: '#F3F4F6', borderRadius: 12, justifyContent: 'center', alignItems: 'center' },

    activeItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#F9FAFB' },
    avatarWrap: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#F3F4F6', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
    avatarImg: { width: 44, height: 44, borderRadius: 22 },
    avatarInitials: { fontSize: 16, fontWeight: '700', color: '#8BA367' },
    activeDot: { position: 'absolute', bottom: 0, right: 0, width: 12, height: 12, borderRadius: 6, backgroundColor: '#10B981', borderWidth: 2, borderColor: '#FFF' },
    inactiveDot: { backgroundColor: '#9CA3AF' },
    moreBtn: { width: 32, height: 32, justifyContent: 'center', alignItems: 'center' },

    // Modals
    anchorOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.2)' },
    anchorPopoverBox: { position: 'absolute', right: 20, backgroundColor: '#FFF', borderRadius: 16, width: 180, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 10, elevation: 5, padding: 4 },
    anchorActionBtn: { flexDirection: 'row', alignItems: 'center', padding: 12, borderBottomWidth: 1, borderBottomColor: '#F3F4F6', gap: 10 },
    anchorActionText: { fontSize: 14, fontWeight: '600', color: '#1E2939' },

    detailModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center', padding: 20 },
    detailCardBox: { backgroundColor: '#FFF', borderRadius: 30, width: '100%', padding: 24, alignItems: 'center', paddingTop: 60 },
    overlapAvatarWrap: { position: 'absolute', top: -50, width: 100, height: 100, borderRadius: 50, backgroundColor: '#FFF', padding: 6, shadowColor: '#000', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.1 },
    ovlAvatarImg: { width: '100%', height: '100%', borderRadius: 44 },
    detailCloseBtn: { position: 'absolute', top: 20, right: 20, width: 36, height: 36, backgroundColor: '#F3F4F6', borderRadius: 18, justifyContent: 'center', alignItems: 'center' },
    detailTitle: { fontSize: 22, fontWeight: '800', color: '#1E2939', marginTop: 10 },
    detailRole: { fontSize: 15, color: '#8BA367', fontWeight: '700', marginBottom: 20 },
    detailGrid: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
    dataCell: { width: '47%' },
    dataLabel: { fontSize: 12, color: '#9CA3AF', marginBottom: 4 },
    dataValue: { fontSize: 14, fontWeight: '700', color: '#4A5565' },

    filterOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.3)' },
    filterPopupBox: { position: 'absolute', right: 20, width: 220, backgroundColor: '#FFF', borderRadius: 20, padding: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.1, shadowRadius: 20, elevation: 10 },
    filterGroupTitle: { fontSize: 13, fontWeight: '800', color: '#9CA3AF', textTransform: 'uppercase', marginBottom: 12, marginLeft: 4 },
    filterOption: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10, paddingHorizontal: 4 },
    filterText: { fontSize: 15, fontWeight: '600', color: '#64748B' },
    filterTextSelected: { color: '#10B981' },
    filterOuterCircle: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: '#E5E7EB', justifyContent: 'center', alignItems: 'center' },
    filterOuterSelected: { borderColor: '#10B981' },
    filterInnerCircle: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#10B981' },
});
