import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const COLORS = {
  background: '#EDE1CE',
  primary: '#8BA367',
  secondary: '#D4B896',
  white: '#FFFFFF',
  textHeader: '#768D57',
  black: '#000000',
  glassOverlay: 'rgba(255, 255, 255, 0.4)',
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  safeArea: {
    flex: 1,
  },
  backgroundElements: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  topCircle: {
    position: 'absolute',
    top: -50,
    left: -50,
    width: 256,
    height: 256,
    borderRadius: 128,
    backgroundColor: COLORS.primary,
    opacity: 0.8,
  },
  bottomCircle: {
    position: 'absolute',
    bottom: -80,
    right: -60,
    width: 288,
    height: 288,
    borderRadius: 144,
    backgroundColor: COLORS.secondary,
    opacity: 0.8,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 50,
    paddingHorizontal: 24,
  },
  headerLogo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logoIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  headerText: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.primary,
  },
  mainCard: {
    width: width * 0.85,
    aspectRatio: 0.9,
    backgroundColor: COLORS.glassOverlay,
    borderRadius: 32,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    elevation: 20,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 25 },
    shadowOpacity: 0.2,
    shadowRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageWrapper: {
    width: '100%',
    height: '100%',
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: COLORS.white,
    position: 'relative',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  starOverlay: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  brandingContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  brandName: {
    fontSize: 48,
    fontWeight: 'normal', // Likely custom font Potta One, using default
    color: COLORS.textHeader,
    marginBottom: 4,
  },
  tagline: {
    fontSize: 16,
    color: '#333333',
    fontWeight: '400',
  },
  button: {
    width: width * 0.85,
    height: 56,
    backgroundColor: COLORS.primary,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
  },
  buttonText: {
    color: COLORS.white,
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: 1.2,
  },
});
