import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

const COLORS = {
  background: '#EDE1CD',
  primary: '#8BA367',
  secondary: '#D4B896',
  white: '#FFFFFF',
  textHeader: '#6D8350',
  textBody: '#6A7282',
  textLabel: '#364153',
  inputBorder: '#E5E7EB',
  inputBg: 'rgba(255, 255, 255, 0.7)',
  glassOverlay: 'rgba(255, 255, 255, 0.8)',
  placeholder: '#99A1AF',
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  backgroundElements: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  circle1: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 224,
    height: 224,
    borderRadius: 112,
    backgroundColor: COLORS.primary,
    opacity: 0.8,
  },
  circle2: {
    position: 'absolute',
    bottom: 80,
    left: -60,
    width: 256,
    height: 256,
    borderRadius: 128,
    backgroundColor: COLORS.secondary,
    opacity: 0.8,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'ios' ? 50 : 30,
    alignItems: 'center',
  },
  headerSection: {
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
  },
  logoContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    marginBottom: 16,
  },
  titleText: {
    fontSize: 28,
    fontWeight: '700',
    color: COLORS.textHeader,
    marginBottom: 4,
  },
  subtitleText: {
    fontSize: 14,
    color: COLORS.textBody,
  },
  card: {
    width: '100%',
    backgroundColor: COLORS.glassOverlay,
    borderRadius: 32,
    padding: 12, // Reduced to show the inner container better or accommodate it
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.08,
    shadowRadius: 30,
    elevation: 5,
  },
  inputContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 24,
    padding: 20,
    paddingTop: 24,
    marginBottom: 20,
  },
  inputGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 13,
    fontWeight: '500',
    color: COLORS.textLabel,
    marginBottom: 6,
    marginLeft: 4,
  },
  input: {
    height: 52,
    backgroundColor: COLORS.inputBg,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.inputBorder,
    paddingHorizontal: 16,
    fontSize: 15,
    color: COLORS.textLabel,
  },
  passwordContainer: {
    position: 'relative',
    justifyContent: 'center',
  },
  passwordInput: {
    paddingRight: 44,
  },
  eyeIcon: {
    position: 'absolute',
    right: 12,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
  },
  consentContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 24,
    paddingHorizontal: 10,
  },
  consentText: {
    fontSize: 13,
    color: COLORS.textBody,
    textAlign: 'center',
    lineHeight: 18,
  },
  linkText: {
    color: COLORS.primary,
    fontWeight: '600',
  },
  registerBtn: {
    height: 52,
    backgroundColor: COLORS.primary,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 8,
  },
  registerBtnText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 1,
  },
  footer: {
    paddingVertical: 24,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  footerText: {
    fontSize: 14,
    color: '#4A5565',
  },
  loginLinkText: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.primary,
    textDecorationLine: 'underline',
  },
});
